-- This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild
--
-- This file is compatible with Lua 5.3

local class = require("class")
local KaitaiStruct = require "kaitaistruct"[1]

local User = class.class(KaitaiStruct)

function User:_init(io, parent, root)
  KaitaiStruct._init(self, io)
  self._parent = parent
  self._root = root or self
  self:_read()
end

function User:_read()
  self.version = self._io:read_u4le()
  self.adventure_level = self._io:read_u4le()
  self.money_div_10 = self._io:read_u4le()
  self.adventure_completed_times = self._io:read_u4le()
  self.survival_day_flags = self._io:read_u4le()
  self.survival_night_flags = self._io:read_u4le()
  self.survival_pool_flags = self._io:read_u4le()
  self.survival_fog_flags = self._io:read_u4le()
  self.survival_roof_flags = self._io:read_u4le()
  self.survival_day_hard_flags = self._io:read_u4le()
  self.survival_night_hard_flags = self._io:read_u4le()
  self.survival_pool_hard_flags = self._io:read_u4le()
  self.survival_fog_hard_flags = self._io:read_u4le()
  self.survival_roof_hard_flags = self._io:read_u4le()
  self.streak_day_endless = self._io:read_u4le()
  self.streak_night_endless = self._io:read_u4le()
  self.streak_pool_endless = self._io:read_u4le()
  self.streak_fog_endless = self._io:read_u4le()
  self.streak_roof_endless = self._io:read_u4le()
  self.trophy_zombotany = self._io:read_u4le()
  self.trophy_wallnut_bowling = self._io:read_u4le()
  self.trophy_slot_machine = self._io:read_u4le()
  self.trophy_raining_seeds = self._io:read_u4le()
  self.trophy_beghouled = self._io:read_u4le()
  self.trophy_invisighoul = self._io:read_u4le()
  self.trophy_seeing_stars = self._io:read_u4le()
  self.trophy_zombiquarium = self._io:read_u4le()
  self.trophy_beghouled_twist = self._io:read_u4le()
  self.trophy_big_trouble_little_zombie = self._io:read_u4le()
  self.trophy_portal_combat = self._io:read_u4le()
  self.trophy_column_like_you_see_em = self._io:read_u4le()
  self.trophy_bobsled_bonanza = self._io:read_u4le()
  self.trophy_zombie_nimble_zombie_quick = self._io:read_u4le()
  self.trophy_whack_a_zombie = self._io:read_u4le()
  self.trophy_last_stand = self._io:read_u4le()
  self.trophy_zombotany_2 = self._io:read_u4le()
  self.trophy_wallnut_bowling_2 = self._io:read_u4le()
  self.trophy_pogo_party = self._io:read_u4le()
  self.trophy_dr_zomboss_revenge = self._io:read_u4le()
  self.trophy_art_challenge_wallnut = self._io:read_u4le()
  self.trophy_sunny_day = self._io:read_u4le()
  self.trophy_unsodded = self._io:read_u4le()
  self.trophy_big_time = self._io:read_u4le()
  self.trophy_art_challenge_sunflower = self._io:read_u4le()
  self.trophy_air_raid = self._io:read_u4le()
  self.trophy_ice_level = self._io:read_u4le()
  self.trophy_zen_garden_limbo = self._io:read_u4le()
  self.trophy_high_gravity = self._io:read_u4le()
  self.trophy_grave_danger = self._io:read_u4le()
  self.trophy_can_you_dig_it = self._io:read_u4le()
  self.trophy_dark_stormy_night = self._io:read_u4le()
  self.trophy_bungee_blitz = self._io:read_u4le()
  self.trophy_squirrel = self._io:read_u4le()
  self.tree_of_wisdom_height = self._io:read_u4le()
  self.trophy_vasebreaker = self._io:read_u4le()
  self.trophy_to_the_left = self._io:read_u4le()
  self.trophy_third_vase = self._io:read_u4le()
  self.trophy_chain_reaction = self._io:read_u4le()
  self.trophy_m_is_for_metal = self._io:read_u4le()
  self.trophy_scary_potter = self._io:read_u4le()
  self.trophy_hokey_pokey = self._io:read_u4le()
  self.trophy_another_chain_reaction = self._io:read_u4le()
  self.trophy_ace_of_vase = self._io:read_u4le()
  self.streak_vasebreaker_endless = self._io:read_u4le()
  self.trophy_i_zombie = self._io:read_u4le()
  self.trophy_i_zombie_too = self._io:read_u4le()
  self.trophy_can_you_dig_it_puzzle = self._io:read_u4le()
  self.trophy_totally_nuts = self._io:read_u4le()
  self.trophy_dead_zeppelin = self._io:read_u4le()
  self.trophy_me_smash = self._io:read_u4le()
  self.trophy_zomboogie = self._io:read_u4le()
  self.trophy_three_hit_wonder = self._io:read_u4le()
  self.trophy_all_your_brainz_r_belong_to_us = self._io:read_u4le()
  self.streak_i_zombie_endless = self._io:read_u4le()
  self.trophy_upsell_limbo = self._io:read_u4le()
  self.trophy_intro_limbo = self._io:read_u4le()
  self.unknown_130_19f = self._io:read_bytes(112)
  self.has_gatling_pea = self._io:read_u4le()
  self.has_twin_sunflower = self._io:read_u4le()
  self.has_gloom_shroom = self._io:read_u4le()
  self.has_cattail = self._io:read_u4le()
  self.has_winter_melon = self._io:read_u4le()
  self.has_gold_magnet = self._io:read_u4le()
  self.has_spikerock = self._io:read_u4le()
  self.has_cob_cannon = self._io:read_u4le()
  self.has_imitater = self._io:read_u4le()
  self.unknown_1c4 = self._io:read_u4le()
  self.marigold_days_left = self._io:read_u4le()
  self.marigold_days_center = self._io:read_u4le()
  self.marigold_days_right = self._io:read_u4le()
  self.has_golden_watering_can = self._io:read_u4le()
  self.fertilizer_amount = self._io:read_u4le()
  self.bug_spray_amount = self._io:read_u4le()
  self.has_phonograph = self._io:read_u4le()
  self.has_gardening_glove = self._io:read_u4le()
  self.has_mushroom_garden = self._io:read_u4le()
  self.has_wheel_barrow = self._io:read_u4le()
  self.stinky_last_awoken = self._io:read_u4le()
  self.seed_slots_minus_6 = self._io:read_u4le()
  self.has_pool_cleaner = self._io:read_u4le()
  self.has_roof_cleaner = self._io:read_u4le()
  self.garden_rake_uses = self._io:read_u4le()
  self.has_aquarium_garden = self._io:read_u4le()
  self.chocolate_amount = self._io:read_u4le()
  self.tree_of_wisdom_available = self._io:read_u4le()
  self.tree_food_amount = self._io:read_u4le()
  self.has_wallnut_first_aid = self._io:read_u4le()
  self.unknown_218_2ef = self._io:read_bytes(216)
  self.almanac_flag = self._io:read_u4le()
  self.stinky_last_chocolate = self._io:read_u4le()
  self.stinky_x = self._io:read_u4le()
  self.stinky_y = self._io:read_u4le()
  self.minigames_unlocked = self._io:read_u4le()
  self.puzzle_mode_unlocked = self._io:read_u4le()
  self.animate_minigame_unlock = self._io:read_u4le()
  self.animate_vasebreaker_unlock = self._io:read_u4le()
  self.animate_i_zombie_unlock = self._io:read_u4le()
  self.animate_survival_unlock = self._io:read_u4le()
  self.animate_limbo_unlock = self._io:read_u4le()
  self.show_adventure_complete = self._io:read_u4le()
  self.has_taco = self._io:read_u4le()
  self.stinky_asleep = self._io:read_u4le()
  self.unknown_328 = self._io:read_u4le()
  self.unknown_32c = self._io:read_u4le()
  self.num_zen_plants = self._io:read_u4le()
  self.zen_plants = {}
  for i = 0, self.num_zen_plants - 1 do
    self.zen_plants[i + 1] = User.ZenPlant(self._io, self, self._root)
  end
  self.home_lawn_security = self._io:read_u2le()
  self.nobel_peas_prize = self._io:read_u2le()
  self.better_off_dead = self._io:read_u2le()
  self.china_shop = self._io:read_u2le()
  self.spudow = self._io:read_u2le()
  self.explodonator = self._io:read_u2le()
  self.morticulturalist = self._io:read_u2le()
  self.dont_pea_in_the_pool = self._io:read_u2le()
  self.roll_some_heads = self._io:read_u2le()
  self.grounded = self._io:read_u2le()
  self.zombologist = self._io:read_u2le()
  self.penny_pincher = self._io:read_u2le()
  self.sunny_days = self._io:read_u2le()
  self.popcorn_party = self._io:read_u2le()
  self.good_morning = self._io:read_u2le()
  self.no_fungus_among_us = self._io:read_u2le()
  self.beyond_the_grave = self._io:read_u2le()
  self.immortal = self._io:read_u2le()
  self.towering_wisdom = self._io:read_u2le()
  self.mustache_mode = self._io:read_u2le()
  self.zombatar_license_accepted = self._io:read_u1()
  self.zombatar_count_duplicate = self._io:read_u4le()
  self.num_zombatars = self._io:read_u4le()
  self.zombatars = {}
  for i = 0, self.num_zombatars - 1 do
    self.zombatars[i + 1] = User.Zombatar(self._io, self, self._root)
  end
end

-- 
-- File format version
-- 0x0A = beta 0.1.1.1014
-- 0x0B = beta 0.9.9.1029
-- 0x0C = final (1.0.0.1051 – 1.2.0.1073)
-- 
-- Current level in Adventure Mode (1–50, extended levels 51–0x7FFFFFFF)
-- 
-- Money divided by 10.
-- 
-- Number of times Adventure Mode completed.
-- 
-- Unknown, normally zero.

User.ZenPlant = class.class(KaitaiStruct)

function User.ZenPlant:_init(io, parent, root)
  KaitaiStruct._init(self, io)
  self._parent = parent
  self._root = root
  self:_read()
end

function User.ZenPlant:_read()
  self.plant_type = self._io:read_u4le()
  self.garden_location = self._io:read_u4le()
  self.column = self._io:read_u4le()
  self.row = self._io:read_u4le()
  self.direction = self._io:read_u4le()
  self.unknown_14 = self._io:read_u4le()
  self.last_watered = self._io:read_u4le()
  self.unknown_1c = self._io:read_u4le()
  self.color = self._io:read_u4le()
  self.times_fertilized = self._io:read_u4le()
  self.times_watered = self._io:read_u4le()
  self.water_needed = self._io:read_u4le()
  self.happiness_state = self._io:read_u4le()
  self.unknown_34 = self._io:read_u4le()
  self.last_phono_bugspray = self._io:read_u4le()
  self.unknown_3c = self._io:read_u4le()
  self.last_fertilized = self._io:read_u4le()
  self.unknown_44 = self._io:read_u4le()
  self.last_chocolate = self._io:read_u4le()
  self.unknown_4c = self._io:read_u4le()
  self.unknown_50 = self._io:read_u4le()
  self.unknown_54 = self._io:read_u4le()
end


User.Zombatar = class.class(KaitaiStruct)

function User.Zombatar:_init(io, parent, root)
  KaitaiStruct._init(self, io)
  self._parent = parent
  self._root = root
  self:_read()
end

function User.Zombatar:_read()
  self.unknown_00 = self._io:read_u4le()
  self.skin_color = self._io:read_u4le()
  self.clothes_type = self._io:read_u4le()
  self.clothes_color = self._io:read_u4le()
  self.tidbits_type = self._io:read_u4le()
  self.tidbits_color = self._io:read_u4le()
  self.accessories_type = self._io:read_u4le()
  self.accessories_color = self._io:read_u4le()
  self.facial_hair_type = self._io:read_u4le()
  self.facial_hair_color = self._io:read_u4le()
  self.hair_type = self._io:read_u4le()
  self.hair_color = self._io:read_u4le()
  self.eyewear_type = self._io:read_u4le()
  self.eyewear_color = self._io:read_u4le()
  self.hat_type = self._io:read_u4le()
  self.hat_color = self._io:read_u4le()
  self.backdrop_type = self._io:read_u4le()
  self.backdrop_color = self._io:read_u4le()
end


return User
